src/FogBugzPd/FogBugzPd.Web/Controllers/FbAccountController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using FogBugzPd.Core;
using FogBugzPd.Core.FbAccountModule;
using FogBugzPd.Core.FogBugzApi;
using FogBugzPd.Infrastructure;
using FogBugzPd.Web.Models.FbAccount;
using FogBugzPd.Application;
using System.Linq;
using FogBugzPd.Infrastructure.Web;
using FogLampz;
using FogLampz.Model;

namespace FogBugzPd.Web.Controllers
{
    public class FbAccountController : ControllerBase
    {
		[HttpGet]
		[CustomAuthorize]
		public ActionResult Settings()
		{
			var fbAccount = DbContext.FbAccounts
			                          .Include("Settings")
			                          .Include("Settings.TestRailConfig")
			                          .Single(a => a.Id == UserContext.FbAccountId);
			FbAccountSettings fbAccountSettings;

			if (fbAccount == null)
				fbAccountSettings = new FbAccountSettings();
			else
				fbAccountSettings = fbAccount.Settings;

			var viewModel = new SettingViewModel();
	
			viewModel.Setup();

			MapSettingsViewModel(viewModel, fbAccountSettings);

			return View("Update", viewModel);
        }

	    [HttpPost]
		[CustomAuthorize]
		public ActionResult Settings(SettingViewModel viewModel)
	    {
			viewModel.Setup();

			if (!ModelState.IsValid)
			{
				return View("Update", viewModel);
			}

			var fbAccount = DbContext.FbAccounts
									.Include("Settings")
									.Include("Settings.TestRailConfig")
									.SingleOrDefault(s => s.Id == viewModel.Id);

			FbAccountSettings fbAccountSettings;

			if (fbAccount == null)
				fbAccountSettings = new FbAccountSettings();
			else
				fbAccountSettings = fbAccount.Settings;

			//refresh cache when qa estimate settings changed
			if (fbAccountSettings.AllowQaEstimates != viewModel.AllowQaEstimates
				|| fbAccountSettings.QaEstimateCustomFieldName != viewModel.QaEstimateCustomFieldname
				|| fbAccountSettings.QaPercentage != viewModel.QaPercentage)
		    {
				CleareCachedCaseSets();
		    }

			MapSettingsEntity(fbAccountSettings, viewModel);

		    var service = new FbAccountService();

		    if (fbAccount != null && fbAccount.Settings != null)
		    {
			    if (fbAccount.Settings.SendDailyDigestEmails)
			    {
					string cacheKeyToken = MsCacheKey.Gen(MsCacheDataType.FogBugz_ClientByFogBugzUrl, UserContext.FogBugzUrl);
				    object fbClientObject = null;
					MsCache.TryGet(cacheKeyToken, ref fbClientObject);
				    var fbClient = (FogBugzClientEx) fbClientObject;
				    fbAccount.Token = fbClient.GetToken();
			    }
			    else
			    {
				    fbAccount.Token = String.Empty;
			    }
		    }

		    // save settings in db
			service.Update(fbAccount);

			var cacheKey = MsCacheKey.Gen(MsCacheDataType.ProjectLists, UserContext.FogBugzUrl);
			MsCache.TryRemove(cacheKey);

			cacheKey = MsCacheKey.Gen(MsCacheDataType.FogBugz_ClientCacheByFogBugzUrl, UserContext.FogBugzUrl);
			MsCache.TryRemove(cacheKey);

			UserContext.SetNotification(PageNotificationType.Success, "Settings have been updated.");

			return RedirectToAction("Settings");
	    }

	    private void MapSettingsViewModel(SettingViewModel viewModel, FbAccountSettings fbAccountSettings)
	    {
			viewModel.Id = fbAccountSettings.Id;
		    viewModel.ResolvedVerifiedStatusId = fbAccountSettings.ResolvedVerifiedStatusId;
			viewModel.AllowSubProjects = fbAccountSettings.AllowSubProjects;
			viewModel.QaPercentage = fbAccountSettings.QaPercentage;
			viewModel.AllowTestRail = fbAccountSettings.AllowTestRail;
			viewModel.AllowSendDailyDigestEmails = fbAccountSettings.SendDailyDigestEmails;

			if (fbAccountSettings.SendDailyDigestEmails)
			{
				viewModel.SendDailyDigestEmailsTo = fbAccountSettings.SendDailyDigestEmailsTo;
			}

			if (fbAccountSettings.TestRailConfig != null)
			{
				viewModel.TestRailUrl = fbAccountSettings.TestRailConfig.Url;
				viewModel.TestRailToken = fbAccountSettings.TestRailConfig.Token;
			}
		    
			viewModel.SubProjectTag = fbAccountSettings.SubProjectTag;

		    viewModel.AllowQaEstimates = fbAccountSettings.AllowQaEstimates;
		    viewModel.QaEstimateCustomFieldname = fbAccountSettings.QaEstimateCustomFieldName;
	    }

		private void MapSettingsEntity(FbAccountSettings entity, SettingViewModel viewModel)
		{
			entity.Id = viewModel.Id;
			entity.ResolvedVerifiedStatusId = viewModel.ResolvedVerifiedStatusId;
			entity.AllowSubProjects = viewModel.AllowSubProjects;
			entity.QaPercentage = viewModel.QaPercentage ?? 0;
			entity.AllowTestRail = viewModel.AllowTestRail;
			entity.SendDailyDigestEmails = viewModel.AllowSendDailyDigestEmails;

			if (entity.SendDailyDigestEmails)
			{
				entity.SendDailyDigestEmailsTo = viewModel.SendDailyDigestEmailsTo;
				entity.Guid = Guid.NewGuid();
			}
			else
			{
				entity.SendDailyDigestEmailsTo = String.Empty;
				entity.Guid = null;
			}

			if (entity.AllowTestRail)
			{
				if(entity.TestRailConfig == null)
					entity.TestRailConfig = new TestRailConfiguration();


				entity.TestRailConfig.Url = viewModel.TestRailUrl;
				entity.TestRailConfig.Token = viewModel.TestRailToken;
			}
			entity.SubProjectTag = viewModel.SubProjectTag;

			entity.AllowQaEstimates = viewModel.AllowQaEstimates;
			entity.QaEstimateCustomFieldName = viewModel.QaEstimateCustomFieldname;
		}

		private void CleareCachedCaseSets()
		{
			IList<FixFor> milestones = FogBugzGateway.GetMilestones();

			milestones.ToList().ForEach(
				milestone =>
				{
					if (milestone.IndexProject.HasValue)
					{
						string cacheKey = MsCacheKey.GenCaseSetKey(milestone.IndexProject.Value, milestone.Index.Value);
						MsCache.TryRemove(cacheKey);
					}
				}
				);


			IList<Case> subProjectParentCases = FogBugzGateway.GetSubProjectParentCases();

			if (subProjectParentCases != null)
				subProjectParentCases.ToList().ForEach(
					parentCase =>
					{
						string cacheKey = MsCacheKey.GenCaseSetKey(parentCase.IndexProject.Value, parentCase.IndexFixFor.Value,
																   parentCase.Index);
						MsCache.TryRemove(cacheKey);
					}
					);

		}
    }
}

src/FogBugzPd/FogBugzPd.Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using FogBugzPd.Application.Extensions;
using FogBugzPd.Core;
using FogBugzPd.Core.FbAccountModule;
using FogBugzPd.Core.FogBugzApi;
using FogBugzPd.Core.ProgressStatus;
using FogBugzPd.Core.ProjectStatus;
using FogBugzPd.Infrastructure;
using FogBugzPd.Web.Models.Project;
using FogBugzPd.Web.Utils;
using FogBugzPd.Web._App_Code.Utils;
using FogLampz;
using FogLampz.Model;

namespace FogBugzPd.Web.Controllers
{
	public class ProjectController : ControllerBase
	{
		//coding convention from http://stackoverflow.com/questions/242534/c-sharp-naming-convention-for-constants

		private static readonly Regex CodeFreezeSubstringRegex = new Regex(
			@"\(CF *(?<month>\d{1,2})/(?<day>\d{1,2})/(?<year>\d{2}(?:\d{2})?)\)",
			RegexOptions.Singleline | RegexOptions.Compiled);

		private const string ProjectStatusKeyPreffix = "ProjectStatusLoader";

		private const string ProjectStatusesKey = "AllKeys";

		private const int DefaultNumOfThreads = 20;

		private const string ListProgressStatusKey = "ProjectListStatusKey";

		[CustomAuthorize]
		public ActionResult Index()
		{
			return RedirectToAction("List");
		}

		[CustomAuthorize]
		public ActionResult List()
		{
			MsCache.Set(ListProgressStatusKey + "_" + UserContext.FogBugzUrl, new ProgressStatusInfo { Value = 0, Label = " Getting projects and milestones..." });

			ViewBag.MasterTitle = "Projects and Milestones";

			return View("List");
		}


		[CustomAuthorize]
		public ActionResult AsyncList(int timeOffest)
		{
			UserContext.TimeZoneOffset = timeOffest;
			var model = CreateListViewModel();

			model.ShowSubProjects = FbAccountContext.Current.Settings.AllowSubProjects;

			var cacheKey = MsCacheKey.Gen(MsCacheDataType.ProjectsStatuses, UserContext.FogBugzUrl);

			object storedObect = null;

			if (!MsCache.TryGet(cacheKey, ref storedObect))
			{

				var projectStatusesLoader = new ProjectStatusListLoader(FbAccountContext.Current.Url);
				projectStatusesLoader.SaveStatusEvent += OnSaveStatus;

				var keys = projectStatusesLoader.BeginGettingProjectStatuses(model.Items);
				MsCache.Set(FbAccountContext.Current.Url + ProjectStatusesKey, keys);
			}

			return PartialView("_AsyncList", model);
		}

		[CustomAuthorize]
		public ActionResult Dashboard(int projectId, int milestoneId, int? subProjectParentCaseId = null)
		{
			if (!MilestoneUtils.CheckNotStarted(projectId, milestoneId, subProjectParentCaseId))
				return RedirectToRoute("DashboardNotStarted");

			var viewModel = new DashboardViewModel();
			viewModel.Setup(projectId, milestoneId, subProjectParentCaseId, true);

			UpdateViewBagForProjectLayout(viewModel);

			return View(viewModel);
		}

		[CustomAuthorize]
		public ActionResult AsyncDashboard(int projectId, int milestoneId, int? subProjectParentCaseId = null)
		{
			var today = DateTime.Today;

			var model = new AsyncDashboardViewModel();
			model.Setup(projectId, milestoneId, subProjectParentCaseId);

			string cacheKey = MsCacheKey.GenCaseSetKey(projectId, milestoneId, subProjectParentCaseId);
			model.MsCache.CreatedAt = MsCache.GetObjectExpirationTime(cacheKey);

			UpdateViewBagForProjectLayout(model);

			IList<Case> cases = new List<Case>();

			Case projectParentCase = null;
			if (subProjectParentCaseId.HasValue)
			{
				var client = FogBugzGateway.GetClientForParallel();
				projectParentCase = client.GetCase(subProjectParentCaseId.Value);
			}

			foreach (var casesWithMilestone in model.CaseSet.Cases.Where(casesWithMilestone => casesWithMilestone.IndexFixFor == milestoneId))
			{
				cases.Add(casesWithMilestone);
			}

			var fbSchedule = FogBugzGateway.GetFbSchedule();

			if (model.CaseSet.Milestone != null)
			{
				model.DatesSection.StartDate = model.CaseSet.Milestone.DateStart;
				if (model.DatesSection.StartDate.HasValue)
				{
					model.DatesSection.StartDateDaysRemaining = DateUtils.Difference(today, model.DatesSection.StartDate.Value);
				}


				model.DatesSection.CodeFreeze = (projectParentCase != null && projectParentCase.DateDue != null) ? projectParentCase.DateDue : MilestoneUtils.CodeFreezeCalculate(projectId, model.Milestone, model.SubProjectParentCaseId, model.CaseSet.Milestone.Name, CodeFreezeSubstringRegex);

				if (model.DatesSection.CodeFreeze.HasValue)
				{
					model.DatesSection.CodeFreezeDaysRemaining = DateUtils.Difference(today, model.DatesSection.CodeFreeze.Value);
					//model.DatesSection.CodeFreezeHolidaysBefore = HolidaysUtils.GetHolidaysInRange(today, model.DatesSection.CodeFreeze.Value);

					model.DatesSection.CodeFreezeHolidaysBefore = fbSchedule.GetSiteScheduledDays(today, model.DatesSection.CodeFreeze.Value).TimeOffRanges;
				}

				model.DatesSection.Rollout = projectParentCase != null ? (model.CaseSet.Milestone.Name.Contains("CF") ? DateUtils.GetCodeFreezeFromName(model.CaseSet.Milestone.Name, CodeFreezeSubstringRegex) : null) : model.CaseSet.Milestone.DateRelease;
				if (model.DatesSection.Rollout.HasValue)
				{
					model.DatesSection.RolloutDaysRemaining = DateUtils.Difference(today, model.DatesSection.Rollout.Value);
					//model.DatesSection.RolloutHolidaysBefore = HolidaysUtils.GetHolidaysInRange(today, model.DatesSection.Rollout.Value);
					model.DatesSection.RolloutHolidaysBefore = fbSchedule.GetSiteScheduledDays(today, model.DatesSection.Rollout.Value).TimeOffRanges;
				}

				CalculatePlotTimes(model.DatesSection);

				model.DatesSection.IsActiveProject = today >= model.DatesSection.StartDate && today <= model.DatesSection.Rollout;
			}

			var persons = FogBugzGateway.GetPersons();
			var isLoadedByAdmin = FogBugzGateway.GetIsScheduleLoadedByAdmin();

			var projectStatusCalculator = new ProjectStatusCalculator(model.CaseSet, persons.ToList(), isLoadedByAdmin, fbSchedule);
			model.ProjectStatus = projectStatusCalculator.GetProjectStatus();

			return PartialView("_AsyncDashboard", model);
		}

		private static void CalculatePlotTimes(AsyncDashboardViewModel.DatesSectionViewModel datesTab)
		{
			var plotTimes = new List<AsyncDashboardViewModel.DatesSectionViewModel.PlotTime>();

			var dtCurrent = DateTime.Now;

			// 0. Start time
			if (datesTab.StartDate.HasValue) plotTimes.Add(new AsyncDashboardViewModel.DatesSectionViewModel.PlotTime("Start Date", datesTab.StartDate.Value));

			// 1. Current time
			plotTimes.Add(new AsyncDashboardViewModel.DatesSectionViewModel.PlotTime("Now", dtCurrent));

			if (datesTab.StartDate.HasValue)
			{
				datesTab.MinimumTime = TimeUtils.Min(dtCurrent, datesTab.StartDate.Value);
			}

			// 2. Code freeze time
			var codeFreeze = datesTab.CodeFreeze;
			if (codeFreeze.HasValue) plotTimes.Add(new AsyncDashboardViewModel.DatesSectionViewModel.PlotTime("Code Freeze", codeFreeze.Value));

			datesTab.MinimumTime = (datesTab.StartDate.HasValue
										? TimeUtils.Min(dtCurrent, datesTab.StartDate.Value)
										: (codeFreeze.HasValue
											   ? TimeUtils.Min(dtCurrent, codeFreeze.Value)
											   : dtCurrent)).AddDays(-7);

			// 3. Release date
			if (datesTab.Rollout != null)
			{
				plotTimes.Add(new AsyncDashboardViewModel.DatesSectionViewModel.PlotTime("Release", datesTab.Rollout.Value));

				datesTab.MaximumTime = TimeUtils.Max(dtCurrent, datesTab.Rollout.Value).AddDays(7);

				datesTab.PlotTimes = plotTimes.OrderBy(plotTime => plotTime.DateTime).ToArray();
			}


		}

		//private static DateTime? GetCodeFreezeFromName(string name)
		//{
		//	Match match = CodeFreezeSubstringRegex.Match(name);

		//	int day, month, year;

		//	if (match.Success &&
		//		int.TryParse(match.Groups["day"].Value, out day) &&
		//		int.TryParse(match.Groups["month"].Value, out month) &&
		//		int.TryParse(match.Groups["year"].Value, out year))
		//	{
		//		if (year < 100) year += 2000;

		//		return new DateTime(year, month, day);
		//	}

		//	return null;
		//}

		[CustomAuthorize]
		public ActionResult Priority(int projectId, int milestoneId, int? subProjectParentCaseId)
		{
			var model = new PriorityViewModel();

			model.Setup(projectId, milestoneId, subProjectParentCaseId);

			string cacheKey = MsCacheKey.GenCaseSetKey(projectId, milestoneId, subProjectParentCaseId);
			model.MsCache.CreatedAt = MsCache.GetObjectExpirationTime(cacheKey);

			UpdateViewBagForProjectLayout(model);

			return View(model);
		}

		[CustomAuthorize]
		public ActionResult Developer(int projectId, int milestoneId, int? subProjectParentCaseId)
		{
			var model = new DeveloperViewModel();

			model.Setup(projectId, milestoneId, subProjectParentCaseId);
			UpdateViewBagForProjectLayout(model);

			string cacheKey = MsCacheKey.GenCaseSetKey(projectId, milestoneId, subProjectParentCaseId);
			model.MsCache.CreatedAt = MsCache.GetObjectExpirationTime(cacheKey);

			return View(model);
		}

		[CustomAuthorize]
		public ActionResult QA(int projectId, int milestoneId, int? subProjectParentCaseId)
		{
			var model = new QAViewModel();

			model.Setup(projectId, milestoneId, subProjectParentCaseId);
			UpdateViewBagForProjectLayout(model);
			var persons = FogBugzGateway.GetPersons();

			string cacheKey = MsCacheKey.GenCaseSetKey(projectId, milestoneId, subProjectParentCaseId);
			model.MsCache.CreatedAt = MsCache.GetObjectExpirationTime(cacheKey);

			IList<Case> cases = new List<Case>();
			foreach (var casesWithMilestone in model.CaseSet.Cases.Where(casesWithMilestone => casesWithMilestone.IndexFixFor == milestoneId))
			{
				cases.Add(casesWithMilestone);
			}

			var qaListItems =
				persons.GroupJoin(cases, person => person.Index, @case => @case.IndexPersonAssignedTo,
								  (person, personCases) =>
								  {
									  var casesArr = personCases.ToArray();
									  return new QAListItem
										  {
											  TesterName = person.Name,
											  Estimate = casesArr.Where(CaseUtils.IsResolved).Sum(@case => CalcEstimateForCase(@case)),

src/FogBugzPd/FogBugzPd.Web/Views/Shared/_Layout.cshtml
@using FogBugzPd.Web
@using FogBugzPd.Web.Models
@using FogBugzPd.Web.Utils
@using FogBugzPd.Infrastructure.Web
@using StackExchange.Profiling
<!DOCTYPE html>
<html>
	<head>
		<title>@ViewBag.Title</title>
	    
        @RenderSection("Meta", false)
		
        <link href="@Url.Content("~/Content/packages/bootstrap/css/bootstrap.css")" rel="stylesheet" type="text/css" />
	    <link href="@Url.ContentV("~/Content/css/style.css")" rel="stylesheet" type="text/css" />
        
	    <style>
			html,
			body {
				height: 100%;
			}
 
			#wrap {
				min-height: 100%;
				height: auto !important;
				height: 100%;
				margin: 0 auto -30px;
			}
			#push,
			#footer {
				height: 30px;
			}
			.profiler-result .label{
				text-transform:none;
			}
		</style>

		@RenderSection("Css", false)
		
	</head>

<body>
	<div id="wrap">
		@if (UserContext.IsLoggedIn)
		{
			@Html.Partial("_TopNavigation")
		}
		
		

        
		<div class="container page-notification">
			<div class="notification" id="notification-div">
				@if (UserContext.PageNotification != null)
	{
					@Html.PageNotification(UserContext.PageNotification.Message, UserContext.PageNotification.Type)
                    UserContext.ResetNotification();
	}
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10">
					<h2>@ViewBag.MasterTitle
						<small>
							@if (ViewBag.WikiPageId != null)
							{
								<a class="wikilink" target="_blank" href="@FogBugzUrlUtils.GetWikiUrl(ViewBag.WikiPageId)"><i class="icon-book"></i></a>
							}
						</small>
					</h2>
				</div>
				<div class="span7" style="width: 300px; float: right">
					<div id="progress-loader" style="display: none; text-align:right;">
						<div class="progress progress-striped active" style="width:300px; float:right; margin-bottom: 0px;">
							<div id = "progress-value" class="progress-bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="90" style="width: 0%">
								<span class="sr-only"></span>
							</div>
						</div>
						<div style="clear: both;"></div>
						<span id="progress-label" style="width:300px; float:left; text-align: left"></span>
					</div>
				</div>
			</div>
			@RenderBody()
		</div>
		<div id="push"></div>
	</div>
	
	<div id="footer">
		<a href="http://www.entechsolutions.com" style="text-decoration: none;"><div class="footer-copy">&copy; 2013 ENTech Solutions &trade;</div></a>
	</div>
	
	<script src="@Url.Content("~/Content/js/jquery-1.8.2.min.js")"></script>
	<script src="@Url.Content("~/Content/packages/bootstrap/js/bootstrap.js")"></script>
	<script src="@Url.Content("~/Content/js/jquery.validate.min.js")"></script>
	<script src="@Url.Content("~/Content/js/jquery.validate.unobtrusive.min.js")"></script>
	<script src="@Url.Content("~/Content/js/additional-methods.min.js")"></script>
    <script src="@Url.Content("~/Content/js/cache.js")"></script>
	<script src="@Url.Content("~/Content/js/common.js")"></script>
	@RenderSection("Js", false)
	
	<script type="text/javascript">
		function resolveUrl(relativeUrl) 
		{
			var webAppRoot = "@Url.Content("~/")";
			var absoluteUrl;
		   
			if (relativeUrl=="~")
				absoluteUrl=webAppRoot;
			else
				absoluteUrl=relativeUrl.replace("~/", webAppRoot);

			return absoluteUrl;
		}
	</script>

	@if (!String.IsNullOrEmpty(EnvironmentConfig.GoogleAnalyticsCode))
	{
		<!-- Google Analytics -->
		<script type="text/javascript">
			(function(i, s, o, g, r, a, m) {
				i['GoogleAnalyticsObject'] = r;
				i[r] = i[r] || function() {
					(i[r].q = i[r].q || []).push(arguments)
				}, i[r].l = 1 * new Date();
				a = s.createElement(o), m = s.getElementsByTagName(o)[0];
				a.async = 1;
				a.src = g;
				m.parentNode.insertBefore(a, m)
			})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

			ga('create', '@EnvironmentConfig.GoogleAnalyticsCode', 'fogbugzpd.com');
			ga('send', 'pageview');

		</script>
	}

	@if (!String.IsNullOrEmpty(EnvironmentConfig.SnapEngageCode))
	{
			<!-- begin SnapEngage code -->
			<script type="text/javascript">
 			(function() {
 				var se = document.createElement('script');
 				se.type = 'text/javascript';
 				se.async = true;
 				se.src = '//commondatastorage.googleapis.com/code.snapengage.com/js/@(EnvironmentConfig.SnapEngageCode).js';
 				var s = document.getElementsByTagName('script')[0];
 				s.parentNode.insertBefore(se, s);
 			})();
 		</script>
			<!-- end SnapEngage code -->
	}
		
	@MiniProfiler.RenderIncludes()
</body>
</html>

src/FogBugzPd/FogBugzPd.Web/Views/Shared/_TopNavigation.cshtml
@using FogBugzPd.Web.Utils

<div class="navbar navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            @{
                var currentUrl = Request.Url.AbsoluteUri;
                var homeUrl = Url.Action("List", "Project", null);
            }

			<ul class="nav">
				<li class="@(currentUrl.Contains(homeUrl) ? "active" : "")"><a href="@homeUrl">Home</a>
				</li>
			</ul>

            @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "btn btn-primary", style = "float:right" })
            
            @if (!EnvironmentConfig.HideSettings)
            {
                @Html.ActionLink("Settings", "Settings", "FbAccount", null, new {@class = "btn btn-primary", style = "float:right;margin-right:5px;"});
            }
        </div>
    </div>
</div>